/**
 * Generates nhost/sql/seed.sql from lib/data.ts (run from repo root: npx tsx scripts/generate-nhost-seed.ts)
 */
import * as fs from "node:fs";
import * as path from "node:path";
import {
  collectionMeta,
  inspiration,
  navDrawer,
  products,
  trendTiles,
} from "../lib/data";

const pills = [
  "Sukoon",
  "Andaaz",
  "Smart Casual",
  "Casual",
  "Tops | Shirts",
  "Belts",
];

const heroes = [
  {
    title: "Ready to Wear",
    subtitle: "Spring Summer '26",
    href: "/collections/ready-to-wear",
    image: "/images/hero-rtw.svg",
  },
  {
    title: "Unstitched",
    subtitle: "Spring Summer '26",
    href: "/collections/unstitched",
    image: "/images/hero-unstitched.svg",
  },
  {
    title: "West",
    subtitle: "Spring Summer '26",
    href: "/collections/west",
    image: "/images/hero-west.svg",
  },
];

const CAT_IDS: Record<string, string> = {
  "ready-to-wear": "11111111-1111-1111-1111-111111111101",
  unstitched: "11111111-1111-1111-1111-111111111102",
  west: "11111111-1111-1111-1111-111111111103",
  "modest-wear": "11111111-1111-1111-1111-111111111104",
  accessories: "11111111-1111-1111-1111-111111111105",
};

function esc(s: string) {
  return s.replace(/'/g, "''");
}

function sqlArray(tags: string[]) {
  return (
    "ARRAY[" +
    tags.map((t) => `'${esc(t)}'`).join(", ") +
    "]::text[]"
  );
}

const lines: string[] = [];
lines.push("-- Generated by scripts/generate-nhost-seed.ts");
lines.push("BEGIN;");
lines.push("");

lines.push("DELETE FROM public.nav_links;");
lines.push("DELETE FROM public.nav_sections;");
lines.push("DELETE FROM public.home_pills;");
lines.push("DELETE FROM public.inspiration_quotes;");
lines.push("DELETE FROM public.trend_tiles;");
lines.push("DELETE FROM public.hero_slides;");
lines.push("DELETE FROM public.products;");
lines.push("DELETE FROM public.categories;");
lines.push("");

const order = [
  "ready-to-wear",
  "unstitched",
  "west",
  "modest-wear",
  "accessories",
] as const;

for (let i = 0; i < order.length; i++) {
  const slug = order[i];
  const meta = collectionMeta[slug];
  lines.push(
    `INSERT INTO public.categories (id, slug, title, description, sort_order) VALUES ('${CAT_IDS[slug]}', '${slug}', '${esc(meta.title)}', '${esc(meta.description)}', ${i});`,
  );
}
lines.push("");

for (const p of products) {
  const catId = CAT_IDS[p.category];
  lines.push(
    `INSERT INTO public.products (sku, slug, name, subtitle, price, currency, category_id, collection, image, new_in, tags) VALUES ('${esc(p.id)}', '${esc(p.slug)}', '${esc(p.name)}', '${esc(p.subtitle)}', ${p.price}, '${esc(p.currency)}', '${catId}', '${esc(p.collection)}', '${esc(p.image)}', ${p.newIn ?? false}, ${sqlArray(p.tags)});`,
  );
}
lines.push("");

heroes.forEach((h, i) => {
  lines.push(
    `INSERT INTO public.hero_slides (title, subtitle, href, image, sort_order) VALUES ('${esc(h.title)}', '${esc(h.subtitle)}', '${esc(h.href)}', '${esc(h.image)}', ${i});`,
  );
});
lines.push("");

trendTiles.forEach((t, i) => {
  lines.push(
    `INSERT INTO public.trend_tiles (title, subtitle, href, sort_order) VALUES ('${esc(t.title)}', '${esc(t.subtitle)}', '${esc(t.href)}', ${i});`,
  );
});
lines.push("");

inspiration.forEach((row, i) => {
  lines.push(
    `INSERT INTO public.inspiration_quotes (quote, name, sort_order) VALUES ('${esc(row.quote)}', '${esc(row.name)}', ${i});`,
  );
});
lines.push("");

pills.forEach((label, i) => {
  lines.push(
    `INSERT INTO public.home_pills (label, sort_order) VALUES ('${esc(label)}', ${i});`,
  );
});
lines.push("");

for (let si = 0; si < navDrawer.length; si++) {
  const section = navDrawer[si];
  const kids = section.children;
  if (kids?.length) {
    const valueRows = kids
      .map(
        (c, ci) =>
          `('${esc(c.label)}', '${esc(c.href)}', ${ci})`,
      )
      .join(",\n    ");
    lines.push(`WITH s AS (
  INSERT INTO public.nav_sections (title, href, sort_order)
  VALUES ('${esc(section.title)}', '${esc(section.href)}', ${si})
  RETURNING id
)
INSERT INTO public.nav_links (section_id, label, href, sort_order)
SELECT s.id, x.label, x.href, x.ord
FROM s
CROSS JOIN (
  VALUES
    ${valueRows}
) AS x(label, href, ord);`);
  } else {
    lines.push(
      `INSERT INTO public.nav_sections (title, href, sort_order) VALUES ('${esc(section.title)}', '${esc(section.href)}', ${si});`,
    );
  }
  lines.push("");
}

lines.push("COMMIT;");

const out = path.join(__dirname, "..", "nhost", "sql", "seed.sql");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, lines.join("\n") + "\n", "utf8");
console.log("Wrote", out);
